name: pathfinder
description: A Dart package for optimized autonomous agent steering behaviors on 2d grid planes. Designed for performance, customization, modularity and ease of adoption (in that order).
version: 0.0.1
repository: https://github.com/BrayFlex/pathfinder
homepage: https://pub.dev/packages/pathfinder

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  vector_math: ^2.1.4 # For Vector2 and related math
  collection: ^1.19.1

dev_dependencies:
  coverage: ^1.11.1
  lints: ^3.0.0
  test: ^1.24.0
